from typing import Callable, Any, Tuple, Iterable, List, TypeAlias
from typing import overload
import torch


@overload
def split(k: int) -> Callable[..., Any]: ...
"""@overload
def split(k: int, r: Tuple[float, float, float]) -> Callable[..., Any]: ...
"""
def get_num_correct(preds: torch.tensor, targets: torch.tensor) -> int: ...
def load_json(json_file: str): ...
def load_dataset(fp: str, rp: str): ...