from typing import Callable, Any, overload
import torch
from datasets.CPSCDataset import CPSCDataset2D


@overload
def split(k: int) -> Callable[..., Any]:  ...
"""@overload
def split(k: int, r: Tuple[float, float, float]) -> Callable[..., Any]: ...
"""
def get_num_correct(preds: torch.tensor, targets: torch.tensor) -> int:  ...
def load_json(json_file: str): ...
def load_dataset(file_path, ref_path) -> CPSCDataset2D:  ...
def load_datasets(file_path, ref_path):  ...
